logging:
  config: "classpath:logback/logback-local.xml"

spring:
  application:
    name: kotlin-server-base
  jpa:
    open-in-view: false
    generate-ddl: false
  data:
    redis:
      repositories:
        enabled: false

kafka:
  topic:
    sample:
      name: sample-topic
      group-id: sample-group