spring:
  application:
    name: kotlin-server-base
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false

kafka:
  topic:
    sample:
      name: sample-topic
      group-id: sample-group